### PR TITLE
Rewrote text alignment method to work with sprites

### PR DESCRIPTION
**Pull request by NathanFlurry**
I rewrote the text alignment code to reposition the text in `CanvasText` instead of moving the sprite or mesh object itself. With the current method of text alignment, sprites appear to behave oddly when rotating. This is because sprites always pivot around the origin of the object, so moving the sprite's position itself based on the text size just moves the entire sprite and does not change the pivot point. However, by doing the text alignment in the canvas itself, the sprite's pivot point will remain the same and the text moves around the pivot point appropriately.

The only downside to using this method is that the canvas size will be about twice as big as required to render the text, since there needs to be a lot of empty space for left and right alignment.

### CODE REVIEW

**Comment by endel** [comment]
Hey @NathanFlurry, 

Thanks for your pull-request. I really wouldn't like to increase the texture size even more though. :(

One major concern of using this library is performance. Each text you create with this library generates a new texture, which will increase your draw calls. It would be awesome to have a single texture in which all texts could share, having just one draw call. (https://github.com/gamestdio/three-text2d/issues/7) - and it would be better to have it as small as possible.

I'll ask you to kindly to remove the `lib/*.js` and `lib/*.d.ts` files. (sorry, the `.gitignore` should be taking care of this already) 

I'll find some time to review during the weekend. 
Thanks!

**Comment by NathanFlurry** [comment]
I fixed the `.gitignore` and added the option to choose the alignment. The `MeshText2D` defaults to child alignment (the old alignment) and the sprite defaults to texture alignment. This is configurable using `TextOptions.alignmentMethod` if the developer wants to switch.

Thanks!

**Comment by NathanFlurry** [comment]
@endel Did you get a chance to look at this PR? Thanks!

**Comment by endel** [comment]
closing this since https://github.com/gamestdio/three-text2d/pull/29 has made into master!

**Pull request closed without merging**
